### ISSUE TITLE
Model file

### ISSUE THREAD

**Issue by Lianglunwei123123** [asdvfghg/ClassBD#1]
能提供一下这个文件吗，想复现一下，非常感谢！

**Comment by fishykj** [comment]
as a new learner, I`m wondering what`s the meaning of 'group_parameters' in 'utils.train_function'

**Comment by fishykj** [comment]
> 能提供一下这个文件吗，想复现一下，非常感谢！

请问您能复现了吗

**Comment by asdvfghg** [comment]
> as a new learner, I`m wondering what`s the meaning of 'group_parameters' in 'utils.train_function'

I’ve uploaded the model structure file for experienced programmers to test with their training programs. I apologize for being busy this month, but I plan to release the entire code next week if possible.

**Comment by fishykj** [comment]
Thanku so much!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jing-Xiao ***@***.***&gt;; 
发送时间: 2024年8月28日(星期三) 上午10:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [asdvfghg/ClassBD] Model file (Issue #1)














  
as a new learner, Im wondering whats the meaning of 'group_parameters' in 'utils.train_function'
  
I’ve uploaded the model structure file for experienced programmers to test with their training programs. I apologize for being busy this month, but I plan to release the entire code next week if possible.

**Comment by fishykj** [comment]
作者您好，这两天我研读了您关于盲解卷积的论文并尝试跑了代码，但结果并不理想，这是我在运行到123 epoch时的结果，后面就没再继续了。想请问一下代码是否还需要细节上的改动来达到更好的训练效果，因为我对代码和数据集基本没有修改，只是在train_local中注释掉了有关JNU的部分，只使用了PU数据集。还请作者指点迷津。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "asdvfghg/ClassBD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月28日(星期三) 上午10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1)





  
as a new learner, Im wondering whats the meaning of 'group_parameters' in 'utils.train_function'
  
I’ve uploaded the model structure file for experienced programmers to test with their training programs. I apologize for being busy this month, but I plan to release the entire code next week if possible.

**Comment by liguge** [comment]
> 作者您好，这两天我研读了您关于盲解卷积的论文并尝试跑了代码，但结果并不理想，这是我在运行到123 epoch时的结果，后面就没再继续了。想请问一下代码是否还需要细节上的改动来达到更好的训练效果，因为我对代码和数据集基本没有修改，只是在train_local中注释掉了有关JNU的部分，只使用了PU数据集。还请作者指点迷津。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "asdvfghg/ClassBD" ***@***.***&gt;; 发送时间:&nbsp;2024年8月28日(星期三) 上午10:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1) as a new learner, Im wondering whats the meaning of 'group_parameters' in 'utils.train_function' I’ve uploaded the model structure file for experienced programmers to test with their training programs. I apologize for being busy this month, but I plan to release the entire code next week if possible. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

没看到您的运行结果啊~

**Comment by fishykj** [comment]
抱歉，不知道为什么没放上来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "asdvfghg/ClassBD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 上午8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1)





  
作者您好，这两天我研读了您关于盲解卷积的论文并尝试跑了代码，但结果并不理想，这是我在运行到123 epoch时的结果，后面就没再继续了。想请问一下代码是否还需要细节上的改动来达到更好的训练效果，因为我对代码和数据集基本没有修改，只是在train_local中注释掉了有关JNU的部分，只使用了PU数据集。还请作者指点迷津。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "asdvfghg/ClassBD" @.&gt;; 发送时间:&nbsp;2024年8月28日(星期三) 上午10:06 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1) as a new learner, Im wondering whats the meaning of 'group_parameters' in 'utils.train_function' I’ve uploaded the model structure file for experienced programmers to test with their training programs. I apologize for being busy this month, but I plan to release the entire code next week if possible. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
没看到您的运行结果啊~

**Comment by fishykj** [comment]
抱歉，不知道为什么没放上来




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "asdvfghg/ClassBD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 上午8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1)





  
作者您好，这两天我研读了您关于盲解卷积的论文并尝试跑了代码，但结果并不理想，这是我在运行到123 epoch时的结果，后面就没再继续了。想请问一下代码是否还需要细节上的改动来达到更好的训练效果，因为我对代码和数据集基本没有修改，只是在train_local中注释掉了有关JNU的部分，只使用了PU数据集。还请作者指点迷津。
 …
 ------------------ 原始邮件 ------------------ 发件人: "asdvfghg/ClassBD" @.&gt;; 发送时间: 2024年8月28日(星期三) 上午10:06 @.&gt;; @.@.&gt;; 主题: Re: [asdvfghg/ClassBD] Model file (Issue #1) as a new learner, Im wondering whats the meaning of 'group_parameters' in 'utils.train_function' I’ve uploaded the model structure file for experienced programmers to test with their training programs. I apologize for being busy this month, but I plan to release the entire code next week if possible. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
没看到您的运行结果啊~

**Comment by asdvfghg** [comment]
你看的应该是验证集的结果，因为验证集采样的样本比较少，所以显示的F1较低，跑完最终推断的测试集结果应该还行。你可以改成跑30-50 epoch看看最终的结果。

**Comment by fishykj** [comment]
作者您好，我把epoch改成了40，训练过程中train_acc还是高的，但val_acc仍不理想，是不是选择的wdcnn模型的参数不够合适，还是如您所说验证集数据过少，又或者有哪些改动可能能使训练集准确率再略高一些。我是故障检测方面的新手，尚学艺不精，还请多多包涵。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "asdvfghg/ClassBD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1)





 
你看的应该是验证集的结果，因为验证集采样的样本比较少，所以显示的F1较低，跑完最终推断的测试集结果应该还行。你可以改成跑30-50 epoch看看最终的结果。

**Comment by asdvfghg** [comment]
ValACC是验证集的结果，用来筛选模型，Test_ACC才是最终测试集的结果。

**Comment by fishykj** [comment]
明白了，我之前的理解有些问题。那请问如何得到测试集的结果？能否提供一下相关代码和数据，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "asdvfghg/ClassBD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月17日(星期四) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [asdvfghg/ClassBD] Model file (Issue #1)





 
ValACC是验证集的结果，用来筛选模型，Test_ACC才是最终测试集的结果。
